### ISSUE TITLE
关于key长度的问题

### ISSUE THREAD

**Issue by zhuwenbing** [Mr-Jos/namesilo_ddns_cli#2]
这个问题是今天发现的。您的脚本里限定了key的长度为24，但是在namesilo上生成的key长度可能会是20、21、24、25（暂且仅测试出这几种长度的key），虽然不影响使用，还是提出来希望大佬可以更新一下，谢谢。

**Comment by Mr-Jos** [comment]
已将key校验标准修改为 长度为16-32的十六进制字符串（兼容大小写）。

**Comment by Mr-Jos** [comment]
真没想到key的长度这么神奇-_-||

**Comment by Mr-Jos** [comment]
这就是我为了解Shell瞎写的第一个脚本，给你解读一下设计理念就明白了。
无依赖：懒得学不必要的函数，还懒得查证各发行版有什么库、没什么库。
低负载：不知道到底需要多少系统资源，还怕自己家的路由器吃不消。
少请求：懒得使用其它域名解析服务，提高检查频率还怕被封。

所以说我不是什么大佬，用不着这么客气，遇到啥问题直接交流即可。

**Comment by zhuwenbing** [comment]
> 这就是我为了解Shell瞎写的第一个脚本，给你解读一下设计理念就明白了。
> 无依赖：懒得学不必要的函数，还懒得查证各发行版有什么库、没什么库。
> 低负载：不知道到底需要多少系统资源，还怕自己家的路由器吃不消。
> 少请求：懒得使用其它域名解析服务，提高检查频率还怕被封。
> 
> 所以说我不是什么大佬，用不着这么客气，遇到啥问题直接交流即可。

好的噢。
